---
    # Install Apache2 and NodeJS on web servers for Dev Environment
  - name: Install Packages for Test Environment
    # host targets
    hosts: webservers hybridservers
    remote_user: root
    # tasks to run on the host targets to install Apache2 and NodeJS
    tasks: 
        # Install Apache2
      - name: Install Apache2
        apt:
          name: apache2
          # ensure that Apache2 is installed and the latest version
          state: latest
        # install NodeJS
      - name: Install NodeJS
        apt:
          name: nodejs
          # ensure that NodeJS is installed and the latest version
          state: latest
      - name: Install Git
        apt:
          name: git
          state: latest

    # Install MariaDB on hybrid servers for Test Environment
  - name: Install Packages for Test Environment
    hosts: hybridservers
    remote_user: root
    tasks:
      - name: Install MariaDB
        apt:
          name: mariadb-server
          state: latest

    # Set up SSH keys on web and hybrid servers for Test Environment by copying the public key to the authorized_keys file and copying the private key to the .ssh directory
  - name: Set up SSH keys
    hosts: webservers hybridservers
    remote_user: root
    become: yes
    vars:
      # the user to add the SSH key to
      ssh_user: tdrobertso42
      # the public key to add to the authorized_keys file
      ssh_public_key: "{{ lookup('file', '/home/tdrobertso42/.ssh/id_rsa.pub') }}"
      # the private key to copy to the .ssh directory
      ssh_private_key: "/home/tdrobertso42/.ssh/id_rsa"
    # tasks to run on the host targets to set up SSH keys
    tasks:
      - name: Add SSH key to authorized keys
        # add the public key to the authorized_keys file
        ansible.builtin.authorized_key:
          user: "{{ ssh_user }}"
          state: present
          key: "{{ ssh_public_key }}"

      # copy the private key to the .ssh directory
      - name: Copy Private SSH key
        copy: 
          # the private key to copy to the .ssh directory
          src: "{{ ssh_private_key }}"
          # the destination of the private key
          dest: "/home/{{ ssh_user }}/.ssh/id_rsa"
          owner: "{{ ssh_user }}"
          group: "{{ ssh_user }}"
          # set permissions of the private key
          mode: '0600'
